name: OTS - OTS APP Pipeline

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]
  workflow_dispatch:


# Variables
env:
  NODE_VERSION: '18.x'                      # set this to the node version to use (e.g. '8.x', '10.x', '12.x')

# Define jobs for each stage
jobs:
  # Build the project
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "$SSH_KEY" > key'
      shell: bash
      env:
        SSH_KEY: ${{secrets.AZURE_CREDENTIALS}}