name: test-main

on:
  push:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Run a one-line script
      run: npm install

  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
    needs: build
    steps:
      - name: Run a online script
        run:  npm run start


  deploy-staging:
    runs-on: ubuntu-latest
    environment:
      name: staging
    needs: deploy-dev
    steps:
      - name: Run a online script
        run: echo Deploy staging

  deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: prod
    needs: deploy-staging
    steps:
      - name: Run a online script
        run: echo Deploy prod