name: test-main

on:
  push:
    branches: [ main ]
  
jobs:

  deploy-dev:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install, build, and test
        run: npm install
        run: sudo npm run start

  deploy-staging:
    runs-on: ubuntu-latest
    environment:
      name: staging
    needs: deploy-dev
    steps:
      - name: Run a online script
        run: echo Deploy staging

  deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: prod
    needs: deploy-staging
    steps:
      - name: Run a online script
        run: echo Deploy prod