name: Reusable workflow PROD

on:
  workflow_call:

jobs:
  build-prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Echo Secret
        run: echo ${{ secrets.TEST_SECRET }}