name: Reusable workflow DEV

on:
  workflow_call:

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Running on dev"

  cypress-dev:
    runs-on: ubuntu-latest
    needs: [build-dev]
    steps:
      - run: |
          echo "Running on dev"