# name: Snyk Scanning

# on:
#     push:
#         branches: [ main ]

# env:
#   SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

# jobs:
#   snyk_scanning_test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Install npm, snyk, and snyk-to-html
#         run: |
#           npm i -g snyk snyk-to-html
#       - name: Authenticate Snyk
#         run: snyk auth $SNYK_TOKEN
#       - name: Run Snyk Test and Generate HTML Report
#         run: |
#           snyk test --org=marcosviniciusmelo --configuration-matching=default --all-sub-projects --severity-threshold=high --json | snyk-to-html -o snyk_results.html
#       - name: Save Report as Artifact
#         uses: actions/upload-artifact@v2
#         with:
#           name: snyk_results
#           path: snyk_results.html
#         if: github.event_name == 'pull_request'

#   snyk_scanning_monitor:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Install npm and snyk
#         run: |
#           npm i -g snyk
#       - name: Authenticate Snyk
#         run: snyk auth $SNYK_TOKEN
#       - name: Run Snyk Monitor
#         run: snyk monitor --org=marcosviniciusmelo --configuration-matching=default --all-sub-projects
#         if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/rel.')
